service: reddelete-hqtrackbot
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: python3.7
  region: us-west-1
  stage: prod

functions:
  reddelete-hqtrackbot:
    handler: handler.run
    events:
      # Invoke Lambda function periodically
      - schedule: rate(12 hours)
    environment:
      REDDIT_CLIENT_ID: ${ssm:RD_REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${ssm:RD_REDDIT_CLIENT_SECRET}
      REDDIT_USERNAME: ${ssm:RD_REDDIT_USERNAME}
      REDDIT_PASSWORD: ${ssm:RD_REDDIT_PASSWORD}
      DELETE_THRESHOLD: 0

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux